project:
  type: website
website:
  title: "Reflections and Simulations"
  description: "Notes on Economics, ML, and Reflections"
  site-url: https://vinayakiyer64.github.io/reflections-and-simulations/ 
  open-graph: true
  twitter-card: true
  navbar:
    right:
      - text: "About"
        href: about.qmd
      - text: "Posts"
        href: index.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    toc: true
    feed: true
    feed-url: index.xml
    css: styles.css

